### PR TITLE
Add Rate limiting

### PR DESCRIPTION
**Pull request by C0D3-M4513R**
This PR adds a rate limit of 1 request per 60s, as recommended in the docs.

### CODE REVIEW

**Comment by Rexios80** [comment]
I appreciate the idea but I don't think this should be handled by the generated SDK. Making bursts of request is a very common use-case, and this would make that impossible. (Assuming this actually does what you say. I don't know rust.)

**Comment by C0D3-M4513R** [comment]
> I appreciate the idea but I don't think this should be handled by the generated SDK. Making bursts of request is a very common use-case, and this would make that impossible. (Assuming this actually does what you say. I don't know rust.)

It would make it impossible to my knowledge. Though to my knowledge, it is way harder to implement correct rate-limiting anywhere else. Maybe letting users manually specify a requwest client might be better?

**Comment by Rexios80** [comment]
Any solution besides hard-coding the rate limit would be better

**Comment by C0D3-M4513R** [comment]
> Any solution besides hard-coding the rate limit would be better

Updated, with a different approach.
You can now dynamically specify a Client at construction time.
This abstraction requires a bit more code, but allows users to use the approach I wanted to use initially.

Edit: I needed to rework it again, because it was too much of a pain to use

**Review by ariesclark — CHANGES_REQUESTED** [review]
Let's clean up this PR a bit.

Can you remove the specification updates from this, things like the new ``Badge``, ``GroupAccessType`` types, ect. Those aren't particularly relevant to rate limiting & make it difficult to see the impact of your changes.

**Comment by C0D3-M4513R** [comment]
I should probably find a better way to do this. A way, that involves less added steps in generate.sh.
Until then I'll close this pr.

**Pull request closed without merging**
