### PR TITLE
fix: invalid text 'null' in request when no args given

### PR DESCRIPTION
**Pull request by paradox8599**
In these requests, if the optional args are None, instead of passing a empty request body, a text 'null' will be added:
image

which results in 400 response saying
```
{
    "error": {
        "message": "JSON failed to parse.",
        "status_code": 400
    }
}
```

This fix checks for the optional args, and only write to the request body if they have values.

It is mainly for `finish_file_data_upload` as it allows an emty body, but the other two will still fail anyway.

### CODE REVIEW

**Review by C0D3-M4513R — CHANGES_REQUESTED** [review]
Please either reformat this pr to automatically apply these patches in generate.sh or edit the underlying specification, from which the rust crate is generated.

**Comment by paradox8599** [comment]
> Please either reformat this pr to automatically apply these patches in generate.sh or edit the underlying specification, from which the rust crate is generated.

Hi! Thanks for your correction. I have tried adding it to `generate.sh`, but running the script result in a lot of other files being changed. Is it expected?

**Comment by Foorack** [comment]
Likely, please attach everything in the PR and we can check. What kind of files?

-------- Original Message --------

**Comment by paradox8599** [comment]
All the changed files are already included in this PR.
I only added a new `sed` command to `generate.sh`, all other files were generated by the script.

**Comment by paradox8599** [comment]
> Likely, please attach everything in the PR and we can check. What kind of files?

All the changed files are already included in this PR.
I only added a new `sed` command to `generate.sh`, all other files were generated by the script.

**Review by Foorack — APPROVED** [review]

**Comment by Foorack** [comment]
Looks good to me. All the other files are just regular updates coming from newer version of the spec.

**Review by C0D3-M4513R — APPROVED** [review]
Also looks good to me now. I'll merge this later today.

**Comment by paradox8599** [comment]
What should I do for future PRs? (if there's any)
Do I only include the `generate.sh` and edited parts?
Or simply everything generated?
Or, how do I `regenerate from 1.18.5 spec` as @C0D3-M4513R did?

**Comment by C0D3-M4513R** [comment]
to do the regeneration, you mainly need to find the released openapi.yaml from the specification repo (https://github.com/vrchatapi/specification).

Doing that requires:
1. find the short commit sha from the latest "release" of the specification, by going to the tags, finding the latest one and grabbing the short hash.
2. go to the `gh-pages` branch, view all commits and search for the commit with that short-hash in it.
3. view that commit (so click on the commit name, but not the hash in the name) and then click: `Browse Files`
4. then click on the `openapi.yaml` file and click on the `Raw` button
5. Copy the url
6. in the `generate.sh` replace the line `-i https://raw.githubusercontent.com/vrchatapi/specification/gh-pages/openapi.yaml \` with `-i {the url you copied} \`

**Comment by C0D3-M4513R** [comment]
> Do I only include the `generate.sh` and edited parts?

Yes, that's the ideal scenario.

**Comment by paradox8599** [comment]
Sure, thank you!

**Pull request merged**
