### PR TITLE
Add multipart content type

### PR DESCRIPTION
**Pull request by jellejurre**

### CODE REVIEW

**Comment by jellejurre** [comment]
This is required for https://github.com/vrchatapi/specification/pull/408 to be merged

**Review by C0D3-M4513R — CHANGES_REQUESTED** [review]
The sed statement changes nothing for me on the master branch.
Even `grep "TODO: support file upload for" src/apis/files_api.rs` comes back with nothing.

Did you want this to be a Draft PR?

**Comment by jellejurre** [comment]
That's corrcect, it only changes stuff from the following pr:

> This is required for [vrchatapi/specification#408](https://github.com/vrchatapi/specification/pull/408) to be merged

**Comment by C0D3-M4513R** [comment]
Okay, but then the documentation of the specification is wrong.
In the specification you write:
```
                file:
                  type: string
                  format: binary
                  description: The binary blob of the png file.
```

Yet in this pr you interpret file as a filename to open and read

**Comment by jellejurre** [comment]
Yes, that's how the generators create it, the generators create a PathBuf, which (as I understand it) store a Path to a file on disk

**Comment by C0D3-M4513R** [comment]
Then the description should read `The path to the file to be uploaded` instead.

**Comment by C0D3-M4513R** [comment]
Also using a blocking file read in an async context is not ideal either in this scenario (though I can totally understand that choice)

**Comment by jellejurre** [comment]
> Then the description should read `The path to the file to be uploaded` instead.

The issue with this is that it depends on the generator :)

The C# generator takes in a byte stream

**Comment by jellejurre** [comment]
> Also using a blocking file read in an async context is not ideal either in this scenario (though I can totally understand that choice)

Honestly the choice was because I don't know almost anything about rust async, I didnt realise that the file reading was sync, I can see if I can turn it into async in a bit

**Comment by C0D3-M4513R** [comment]
> I can see if I can turn it into async in a bit

With the current dependencies `std` it's imo not possible.
We'll have to pull in some helper crate(s). Something like `async-std` or `tokio` (though I think the first choice is more versatile for consumers)

**Comment by jellejurre** [comment]
Ah

Well realistically the images won't be too big so do we think that's worth it?

I feel like it might be fine like this

**Comment by C0D3-M4513R** [comment]
Oh also you use `.unwrap()`, which is 100% off-limits for us as a crate.

**Comment by jellejurre** [comment]
Yeah that's fair lol

**Comment by C0D3-M4513R** [comment]
@jellejurre Can you look at these changes?

**Comment by C0D3-M4513R** [comment]
Wait, now that I'm thinking about it again, couldn't we just patch the sdk and have the user supply s byte stream and mime type?

Is that a better approach?

**Comment by jellejurre** [comment]
Looks good to me, works and gives a proper error when handing a non-existent file

**Comment by jellejurre** [comment]
> Wait, now that I'm thinking about it again, couldn't we just patch the sdk and have the user supply s byte stream and mime type?
> 
> Is that a better approach?

Also possible, fine by me and probably more extendable in the long run

**Comment by C0D3-M4513R** [comment]
Writing a regex replace in regex101.com for that is no problem, but I can't get the regex to actually work.

**Comment by jellejurre** [comment]
honestly, throw the regex in chatgpt, it's great at regexes lol

**Review by C0D3-M4513R — APPROVED** [review]
I finally got the regex.
I couldn't use sed, because it isn't powerful enough.

**Comment by C0D3-M4513R** [comment]
Only thing left is to test this again and then to merge (if you have perms, feel free to merge yourself. If not, I'll merge it, when you said, that it works)

**Comment by jellejurre** [comment]
let mut buffer = Vec::new();
    let a = File::open("./image.png").unwrap().read_to_end(&mut buffer);
    let output = vrchatapi::apis::files_api::upload_icon(&config, buffer, "image.png", "image/png")
        .await
        .unwrap();
        
this works great, LGTM

**Pull request merged**
